# Changes here will be overwritten by Copier
_commit: e392033
_src_path: https://github.com/python-project-templates/base.git
add_docs: true
add_extension: rust
add_wiki: false
email: prettygoodcapital@gmail.com
github: prettygoodcapital
project_description: Standard financial enumerations
project_name: finance enums
python_version_primary: '3.11'
team: PrettyGoodCapital
