// Static data tables for finance enums.
// Currency tables are maintained in `currency_data.rs` as structured records.
#![allow(dead_code, non_upper_case_globals)]

pub use crate::currency_data::{
    currency_record, CurrencyAliasRecord, CurrencyAliasRecordRaw, CurrencyDataExportV1,
    CurrencyName_ARRAY, CurrencyRecord, CurrencyRecordRaw, Currency_ALIASES, Currency_CODES_ARRAY,
    Currency_VARIANTS, Currency_names_ARRAY, CURRENCY_ALIAS_RECORDS, CURRENCY_ALIAS_RECORDS_RAW,
    CURRENCY_EXPORT_ABI_VERSION, CURRENCY_EXPORT_V1, CURRENCY_RECORDS, CURRENCY_RECORDS_RAW,
};

pub static AgricultureType_VARIANTS: &[&str] = &[
    "Corn",
    "Wheat",
    "Oats",
    "Soybean",
    "Cocoa",
    "Coffee",
    "Sugar",
    "Cotton",
    "OrangeJuice",
    "Cattle",
    "Hogs",
];
pub static BondType_VARIANTS: &[&str] = &["Corporate", "Government", "Municipal"];
pub static CommodityType_VARIANTS: &[&str] = &["Energy", "Metals", "Agriculture"];
pub static CountryCode_VARIANTS: &[&str] = &[
    "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ",
    "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS",
    "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN",
    "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE",
    "EG", "EH", "ER", "ES", "ET", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF",
    "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM",
    "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM",
    "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC",
    "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK",
    "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA",
    "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG",
    "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW",
    "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS",
    "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO",
    "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI",
    "VN", "VU", "WF", "WS", "XX", "YE", "YT", "ZA", "ZM", "ZW",
];
pub static CountryCode3_VARIANTS: &[&str] = &[
    "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS",
    "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM",
    "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK",
    "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV",
    "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY",
    "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD",
    "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM",
    "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN",
    "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM",
    "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA",
    "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL",
    "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI",
    "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU",
    "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI",
    "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC",
    "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD",
    "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS",
    "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY",
    "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "XXX", "YEM", "MYT",
    "ZAF", "ZMB", "ZWE",
];
pub static EnergyType_VARIANTS: &[&str] = &["Crude", "NaturalGas"];
pub static EquityType_VARIANTS: &[&str] = &[
    "Shares",
    "PreferredShares",
    "ConvertibleShares",
    "PreferredConvertibleShares",
    "DepositoryReceipt",
];
pub static ExchangeCode_VARIANTS: &[&str] = &[
    "XNYS", "NYSD", "XCIS", "CISD", "XCHI", "ARCX", "ARCD", "ARCO", "XASE", "AMXO", "XNAS", "XNGS",
    "XNCM", "XNMS", "NASD", "XNDQ", "XBOS", "BOSD", "XBXO", "XPHL", "XPSX", "PSXD", "XPHO", "XPBT",
    "XPOR", "XNFI", "EDGA", "EDGD", "EDGX", "EDDP", "EDGO", "BATS", "BZXD", "BATO", "BATY", "BYXD",
    "MEMX", "MEMD", "IEXG", "LTSE", "MIHI", "MPRL", "EPRL", "EPRD", "XMIO", "EMLD", "XISE", "GMNI",
    "MCRY", "XCBO", "C2OX", "MXOP", "OPRA", "OTCM", "CAVE", "OTCB", "OTCQ", "PINL", "PINI", "PINX",
    "PSGM", "PINC", "FINR", "FINN", "FINC", "FINY", "XADF", "FINO", "OOTC", "XCME", "FCME", "GLBX",
    "XCBT", "FCBT", "XKBT", "XNYM", "XTSE", "XDRK", "VDRK", "XTSX", "XTNX", "XATS", "XATX", "ADRK",
    "XMOD", "XMOC", "NEOE", "NEOD", "NEON", "NEOC", "XCNQ", "PURE", "CSE2", "XLON", "XTKS", "XHKG",
    "XSHG", "XEUR", "XPAR", "XFRA", "XASX", "XBOM", "XNSE", "XAMS", "XBRU", "XLIS", "XMIL", "XMAD",
    "XSWX", "XOSL", "XSTO", "XHEL", "XCSE", "XICE", "XWAR", "XPRA", "XBUD", "XWBO", "XDUB", "XKRX",
    "XSES", "XTAI", "XBKK", "XKLS", "XIDX", "XPHS", "XNZE", "XJSE", "XSAU", "XIST", "XTAE", "XDFM",
    "XADS", "BVMF", "XMEX", "XBUE", "XSGO", "XLIM", "XBOG", "XXXX", "PYPR", "SIMU", "FOREX",
    "CRYPTO", "SIFMA_US", "ICE_US", "CFE",
];
pub static FundSubType_VARIANTS: &[&str] = &["Index", "Sector", "Active", "Passive"];
pub static FundType_VARIANTS: &[&str] = &["ETF", "MutualFund", "REIT"];
pub static FutureDeliveryType_VARIANTS: &[&str] = &["Physical", "Cash"];
pub static FutureType_VARIANTS: &[&str] = &["Financial", "Commodity"];
pub static Industry_VARIANTS: &[&str] = &[
    "EnergyEquipmentAndServices",
    "OilGasAndConsumableFuels",
    "Chemicals",
    "ConstructionMaterials",
    "ContainersAndPackaging",
    "MetalsAndMining",
    "PaperAndForestProducts",
    "AerospaceAndDefense",
    "BuildingProducts",
    "ConstructionAndEngineering",
    "ElectricalEquipment",
    "IndustrialConglomerates",
    "Machinery",
    "TradingCompaniesAndDistributors",
    "CommercialServicesAndSupplies",
    "ProfessionalServices",
    "AirFreightAndLogistics",
    "PassengerAirlines",
    "MarineTransportation",
    "GroundTransportation",
    "TransportationInfrastructure",
    "AutomobileComponents",
    "Automobiles",
    "HouseholdDurables",
    "LeisureProducts",
    "TextilesApparelAndLuxuryGoods",
    "HotelsRestaurantsAndLeisure",
    "DiversifiedConsumerServices",
    "Distributors",
    "BroadlineRetail",
    "SpecialtyRetail",
    "ConsumerStaplesDistributionAndRetail",
    "Beverages",
    "FoodProducts",
    "Tobacco",
    "HouseholdProducts",
    "PersonalCareProducts",
    "HealthCareEquipmentAndSupplies",
    "HealthCareProvidersAndServices",
    "HealthCareTechnology",
    "Biotechnology",
    "Pharmaceuticals",
    "LifeSciencesToolsAndServices",
    "Banks",
    "FinancialServices",
    "ConsumerFinance",
    "CapitalMarkets",
    "MortgageRealEstateInvestmentTrusts",
    "Insurance",
    "ITServices",
    "Software",
    "CommunicationsEquipment",
    "TechnologyHardwareStorageAndPeripherals",
    "ElectronicEquipmentInstrumentsAndComponents",
    "SemiconductorsAndSemiconductorEquipment",
    "DiversifiedTelecommunicationServices",
    "WirelessTelecommunicationServices",
    "Media",
    "Entertainment",
    "InteractiveMediaAndServices",
    "ElectricUtilities",
    "GasUtilities",
    "MultiUtilities",
    "WaterUtilities",
    "IndependentPowerAndRenewableElectricityProducers",
    "DiversifiedREITs",
    "IndustrialREITs",
    "HotelAndResortREITs",
    "OfficeREITs",
    "HealthCareREITs",
    "ResidentialREITs",
    "RetailREITs",
    "SpecializedREITs",
    "RealEstateManagementAndDevelopment",
];
pub static IndustryGroup_VARIANTS: &[&str] = &[
    "Energy",
    "Materials",
    "CapitalGoods",
    "CommercialAndProfessionalServices",
    "Transportation",
    "AutomobilesAndComponents",
    "ConsumerDurablesAndApparel",
    "ConsumerServices",
    "ConsumerDiscretionaryDistributionAndRetail",
    "ConsumerStaplesDistributionAndRetail",
    "FoodBeverageAndTobacco",
    "HouseholdAndPersonalProducts",
    "HealthCareEquipmentAndServices",
    "PharmaceuticalsBiotechnologyAndLifeSciences",
    "Banks",
    "FinancialServices",
    "Insurance",
    "SoftwareAndServices",
    "TechnologyHardwareAndEquipment",
    "SemiconductorsAndSemiconductorEquipment",
    "TelecommunicationServices",
    "MediaAndEntertainment",
    "Utilities",
    "EquityRealEstateInvestmentTrusts",
    "RealEstateManagementAndDevelopment",
];
pub static InstrumentType_VARIANTS: &[&str] = &[
    "Spot", "Option", "Forward", "Future", "Right", "Spread", "Pair", "Basket",
];
pub static MetalsType_VARIANTS: &[&str] = &["Gold", "Silver", "Copper", "Platinum", "Palladium"];
pub static MutualFundEndedness_VARIANTS: &[&str] = &["Open", "Close"];
pub static OptionExerciseType_VARIANTS: &[&str] = &["American", "European", "Bermudan"];
pub static OptionType_VARIANTS: &[&str] = &["Call", "Put"];
pub static OrderFlag_VARIANTS: &[&str] = &["None", "FillOrKill", "AllOrNone", "ImmediateOrCancel"];
pub static OrderType_VARIANTS: &[&str] = &["Limit", "Market", "Stop"];
pub static Sector_VARIANTS: &[&str] = &[
    "Energy",
    "Materials",
    "Industrials",
    "ConsumerDiscretionary",
    "ConsumerStaples",
    "HealthCare",
    "Financials",
    "InformationTechnology",
    "CommunicationServices",
    "Utilities",
    "RealEstate",
];
pub static SecurityType_VARIANTS: &[&str] = &[
    "Equity",
    "Option",
    "Bond",
    "Forward",
    "Future",
    "PerpetualFuture",
    "Spread",
    "Fund",
    "Commodity",
    "Currency",
    "Pair",
    "Index",
];
pub static Side_VARIANTS: &[&str] = &["None", "Buy", "Sell"];
pub static SubIndustry_VARIANTS: &[&str] = &[
    "OilAndGasDrilling",
    "OilAndGasEquipmentAndServices",
    "IntegratedOilAndGas",
    "OilAndGasExplorationAndProduction",
    "OilAndGasRefiningAndMarketing",
    "OilAndGasStorageAndTransportation",
    "CoalAndConsumableFuels",
    "CommodityChemicals",
    "DiversifiedChemicals",
    "FertilizersAndAgriculturalChemicals",
    "IndustrialGases",
    "SpecialtyChemicals",
    "ConstructionMaterials",
    "MetalGlassAndPlasticContainers",
    "PaperAndPlasticPackagingProductsAndMaterials",
    "Aluminum",
    "DiversifiedMetalsAndMining",
    "Copper",
    "Gold",
    "PreciousMetalsAndMinerals",
    "Silver",
    "Steel",
    "ForestProducts",
    "PaperProducts",
    "AerospaceAndDefense",
    "BuildingProducts",
    "ConstructionAndEngineering",
    "ElectricalComponentsAndEquipment",
    "HeavyElectricalEquipment",
    "IndustrialConglomerates",
    "ConstructionMachineryAndHeavyTransportationEquipment",
    "AgriculturalAndFarmMachinery",
    "IndustrialMachinerySuppliesAndComponents",
    "TradingCompaniesAndDistributors",
    "CommercialPrinting",
    "EnvironmentalAndFacilitiesServices",
    "OfficeServicesAndSupplies",
    "DiviersifiedSupportServices",
    "SecurityAndAlarmServices",
    "HumanResourcesAndEmploymentServices",
    "ResearchAndConsultingServices",
    "DataProcessingAndOutsourcedServices",
    "AirFreightAndLogistics",
    "PassengerAirlines",
    "MarineTransportation",
    "RailTransportation",
    "CargoGroundTransportation",
    "PassengerGroundTransportation",
    "AirportServices",
    "HighwaysAndRailtracks",
    "MarinePortsAndServices",
    "AutomotivePartsAndEquipment",
    "TiresAndRubber",
    "AutomobileManufacturers",
    "MotorcycleManufacturers",
    "ConsumerElectronics",
    "HomeFurnishings",
    "Homebuilding",
    "HouseholdAppliances",
    "HousewaresAndSpecialties",
    "LeisureProducts",
    "ApparelAccessoriesAndLuxuryGoods",
    "Footwear",
    "Textiles",
    "CasinosAndGaming",
    "HotelsResortsAndCruiseLines",
    "LeisureFacilities",
    "Restaurants",
    "EducationServices",
    "SpecializedConsumerServices",
    "Distributors",
    "BroadlineRetail",
    "ApparelRetail",
    "ComputerAndElectronicsretail",
    "HomeImprovementRetail",
    "OtherSpecialtyRetail",
    "AutomotiveRetail",
    "HomefurnishingRetail",
    "DrugRetail",
    "FoodDistributors",
    "FoodRetail",
    "ConsumerStaplesMerchandiseRetail",
    "Brewers",
    "DistillersAndVintners",
    "SoftDrinksAndNonAlcoholicBeverages",
    "AgriculturalProductsAndServices",
    "PackagedFoodsAndMeats",
    "Tobacco",
    "HouseholdProducts",
    "PersonalCareProducts",
    "HealthCareEquipment",
    "HealthCareSupplies",
    "HealthCareDistributors",
    "HealthCareServices",
    "HealthCareFacilities",
    "ManagedHealthCare",
    "HealthCareTechnology",
    "Biotechnology",
    "Pharmaceuticals",
    "LifeSciencesToolsAndServices",
    "DiversifiedBanks",
    "RegionalBanks",
    "DiversifiedFinancialServices",
    "MultiSectorHoldings",
    "SpecializedFinance",
    "CommercialAndResidentialMortgageFinance",
    "TransactionAndPaymentProcessingServices",
    "ConsumerFinance",
    "AssetManagementAndCustodyBanks",
    "InvestmentBankingAndBrokerage",
    "DiversifiedCapitalMarkets",
    "FinancialExchangesAndData",
    "MortgageRealEstateInvestmentTrusts",
    "InsuranceBrokers",
    "LifeAndHealthInsurance",
    "MultilineInsurance",
    "PropertyAndCasualtyInsurance",
    "Reinsurance",
    "ITConsultingAndOtherServices",
    "InternetServicesAndInfrastructure",
    "ApplicationSoftware",
    "SystemsSoftware",
    "CommunicationsEquipment",
    "TechnologyHardwareStorageAndPeripherals",
    "ElectronicEquipmentAndInstruments",
    "ElectronicComponents",
    "ElectronicManufacturingServices",
    "TechnologyDistributors",
    "SemiconductorMaterialsAndEquipment",
    "Semiconductors",
    "AlternativeCarriers",
    "IntegratedTelecommunicationServices",
    "WirelessTelecommunicationServices",
    "Advertising",
    "Broadcasting",
    "CableAndSatellite",
    "Publishing",
    "MoviesAndEntertainment",
    "InteractiveHomeEntertainment",
    "InteractiveMediaAndServices",
    "ElectricUtilities",
    "GasUtilities",
    "MultiUtilities",
    "WaterUtilities",
    "IndependentPowerProducersAndEnergyTraders",
    "RenewableElectricity",
    "DiversifiedREITs",
    "IndustrialREITs",
    "HotelAndResortREITs",
    "OfficeREITs",
    "HealthCareREITs",
    "MultiFamilyResidentialREITs",
    "SingleFamilyResidentialREITs",
    "RetailREITs",
    "OtherSpecializedREITs",
    "SelfStorageREITs",
    "TelecomTowerREITs",
    "TimberREITs",
    "DataCenterREITs",
    "DiversifiedRealEstateActivities",
    "RealEstateOperatingCompanies",
    "RealEstateDevelopment",
    "RealEstateServices",
];
pub static TimeInForce_VARIANTS: &[&str] = &["None", "Day", "GoodTillCanceled"];
pub static TradingType_VARIANTS: &[&str] = &["Live", "Simulation", "Sandbox", "Backtest"];
pub static CountryCode3_names_ARRAY: &[&str] = &[
    "AND", "ARE", "AFG", "ATG", "AIA", "ALB", "ARM", "AGO", "ATA", "ARG", "ASM", "AUT", "AUS",
    "ABW", "ALA", "AZE", "BIH", "BRB", "BGD", "BEL", "BFA", "BGR", "BHR", "BDI", "BEN", "BLM",
    "BMU", "BRN", "BOL", "BES", "BRA", "BHS", "BTN", "BVT", "BWA", "BLR", "BLZ", "CAN", "CCK",
    "COD", "CAF", "COG", "CHE", "CIV", "COK", "CHL", "CMR", "CHN", "COL", "CRI", "CUB", "CPV",
    "CUW", "CXR", "CYP", "CZE", "DEU", "DJI", "DNK", "DMA", "DOM", "DZA", "ECU", "EST", "EGY",
    "ESH", "ERI", "ESP", "ETH", "FIN", "FJI", "FLK", "FSM", "FRO", "FRA", "GAB", "GBR", "GRD",
    "GEO", "GUF", "GGY", "GHA", "GIB", "GRL", "GMB", "GIN", "GLP", "GNQ", "GRC", "SGS", "GTM",
    "GUM", "GNB", "GUY", "HKG", "HMD", "HND", "HRV", "HTI", "HUN", "IDN", "IRL", "ISR", "IMN",
    "IND", "IOT", "IRQ", "IRN", "ISL", "ITA", "JEY", "JAM", "JOR", "JPN", "KEN", "KGZ", "KHM",
    "KIR", "COM", "KNA", "PRK", "KOR", "KWT", "CYM", "KAZ", "LAO", "LBN", "LCA", "LIE", "LKA",
    "LBR", "LSO", "LTU", "LUX", "LVA", "LBY", "MAR", "MCO", "MDA", "MNE", "MAF", "MDG", "MHL",
    "MKD", "MLI", "MMR", "MNG", "MAC", "MNP", "MTQ", "MRT", "MSR", "MLT", "MUS", "MDV", "MWI",
    "MEX", "MYS", "MOZ", "NAM", "NCL", "NER", "NFK", "NGA", "NIC", "NLD", "NOR", "NPL", "NRU",
    "NIU", "NZL", "OMN", "PAN", "PER", "PYF", "PNG", "PHL", "PAK", "POL", "SPM", "PCN", "PRI",
    "PSE", "PRT", "PLW", "PRY", "QAT", "REU", "ROU", "SRB", "RUS", "RWA", "SAU", "SLB", "SYC",
    "SDN", "SWE", "SGP", "SHN", "SVN", "SJM", "SVK", "SLE", "SMR", "SEN", "SOM", "SUR", "SSD",
    "STP", "SLV", "SXM", "SYR", "SWZ", "TCA", "TCD", "ATF", "TGO", "THA", "TJK", "TKL", "TLS",
    "TKM", "TUN", "TON", "TUR", "TTO", "TUV", "TWN", "TZA", "UKR", "UGA", "UMI", "USA", "URY",
    "UZB", "VAT", "VCT", "VEN", "VGB", "VIR", "VNM", "VUT", "WLF", "WSM", "XXX", "YEM", "MYT",
    "ZAF", "ZMB", "ZWE",
];
pub static CountryCode_names_ARRAY: &[&str] = &[
    "AD", "AE", "AF", "AG", "AI", "AL", "AM", "AO", "AQ", "AR", "AS", "AT", "AU", "AW", "AX", "AZ",
    "BA", "BB", "BD", "BE", "BF", "BG", "BH", "BI", "BJ", "BL", "BM", "BN", "BO", "BQ", "BR", "BS",
    "BT", "BV", "BW", "BY", "BZ", "CA", "CC", "CD", "CF", "CG", "CH", "CI", "CK", "CL", "CM", "CN",
    "CO", "CR", "CU", "CV", "CW", "CX", "CY", "CZ", "DE", "DJ", "DK", "DM", "DO", "DZ", "EC", "EE",
    "EG", "EH", "ER", "ES", "ET", "FI", "FJ", "FK", "FM", "FO", "FR", "GA", "GB", "GD", "GE", "GF",
    "GG", "GH", "GI", "GL", "GM", "GN", "GP", "GQ", "GR", "GS", "GT", "GU", "GW", "GY", "HK", "HM",
    "HN", "HR", "HT", "HU", "ID", "IE", "IL", "IM", "IN", "IO", "IQ", "IR", "IS", "IT", "JE", "JM",
    "JO", "JP", "KE", "KG", "KH", "KI", "KM", "KN", "KP", "KR", "KW", "KY", "KZ", "LA", "LB", "LC",
    "LI", "LK", "LR", "LS", "LT", "LU", "LV", "LY", "MA", "MC", "MD", "ME", "MF", "MG", "MH", "MK",
    "ML", "MM", "MN", "MO", "MP", "MQ", "MR", "MS", "MT", "MU", "MV", "MW", "MX", "MY", "MZ", "NA",
    "NC", "NE", "NF", "NG", "NI", "NL", "NO", "NP", "NR", "NU", "NZ", "OM", "PA", "PE", "PF", "PG",
    "PH", "PK", "PL", "PM", "PN", "PR", "PS", "PT", "PW", "PY", "QA", "RE", "RO", "RS", "RU", "RW",
    "SA", "SB", "SC", "SD", "SE", "SG", "SH", "SI", "SJ", "SK", "SL", "SM", "SN", "SO", "SR", "SS",
    "ST", "SV", "SX", "SY", "SZ", "TC", "TD", "TF", "TG", "TH", "TJ", "TK", "TL", "TM", "TN", "TO",
    "TR", "TT", "TV", "TW", "TZ", "UA", "UG", "UM", "US", "UY", "UZ", "VA", "VC", "VE", "VG", "VI",
    "VN", "VU", "WF", "WS", "XX", "YE", "YT", "ZA", "ZM", "ZW",
];
pub static CountryNames_ARRAY: &[&str] = &[
    "Andorra",
    "United Arab Emirates",
    "Afghanistan",
    "Antigua and Barbuda",
    "Anguilla",
    "Albania",
    "Armenia",
    "Angola",
    "Antarctica",
    "Argentina",
    "American Samoa",
    "Austria",
    "Australia",
    "Aruba",
    "Åland Islands",
    "Azerbaijan",
    "Bosnia and Herzegovina",
    "Barbados",
    "Bangladesh",
    "Belgium",
    "Burkina Faso",
    "Bulgaria",
    "Bahrain",
    "Burundi",
    "Benin",
    "Saint Barthélemy",
    "Bermuda",
    "Brunei Darussalam",
    "Bolivia",
    "Bonaire",
    "Brazil",
    "Bahamas",
    "Bhutan",
    "Bouvet Island",
    "Botswana",
    "Belarus",
    "Belize",
    "Canada",
    "Cocos (Keeling) Islands",
    "Democratic Republic of the Congo",
    "Central African Republic",
    "Congo",
    "Switzerland",
    "Côte d'Ivoire",
    "Cook Islands",
    "Chile",
    "Cameroon",
    "China",
    "Colombia",
    "Costa Rica",
    "Cuba",
    "Cabo Verde",
    "Curaçao",
    "Christmas Island",
    "Cyprus",
    "Czechia",
    "Germany",
    "Djibouti",
    "Denmark",
    "Dominica",
    "Dominican Republic",
    "Algeria",
    "Ecuador",
    "Estonia",
    "Egypt",
    "Western Sahara",
    "Eritrea",
    "Spain",
    "Ethiopia",
    "Finland",
    "Fiji",
    "Falkland Islands",
    "Micronesia",
    "Faroe Islands",
    "France",
    "Gabon",
    "United Kingdom of Great Britain and Northern Ireland",
    "Grenada",
    "Georgia",
    "French Guiana",
    "Guernsey",
    "Ghana",
    "Gibraltar",
    "Greenland",
    "Gambia",
    "Guinea",
    "Guadeloupe",
    "Equatorial Guinea",
    "Greece",
    "South Georgia and the South Sandwich Islands",
    "Guatemala",
    "Guam",
    "Guinea-Bissau",
    "Guyana",
    "Hong Kong",
    "Heard Island and McDonald Islands",
    "Honduras",
    "Croatia",
    "Haiti",
    "Hungary",
    "Indonesia",
    "Ireland",
    "Israel",
    "Isle of Man",
    "India",
    "British Indian Ocean Territory",
    "Iraq",
    "Iran",
    "Iceland",
    "Italy",
    "Jersey",
    "Jamaica",
    "Jordan",
    "Japan",
    "Kenya",
    "Kyrgyzstan",
    "Cambodia",
    "Kiribati",
    "Comoros",
    "Saint Kitts and Nevis",
    "North Korea",
    "South Korea",
    "Kuwait",
    "Cayman Islands",
    "Kazakhstan",
    "Laos",
    "Lebanon",
    "Saint Lucia",
    "Liechtenstein",
    "Sri Lanka",
    "Liberia",
    "Lesotho",
    "Lithuania",
    "Luxembourg",
    "Latvia",
    "Libya",
    "Morocco",
    "Monaco",
    "Moldova",
    "Montenegro",
    "Saint Martin",
    "Madagascar",
    "Marshall Islands",
    "North Macedonia",
    "Mali",
    "Myanmar",
    "Mongolia",
    "Macao",
    "Northern Mariana Islands",
    "Martinique",
    "Mauritania",
    "Montserrat",
    "Malta",
    "Mauritius",
    "Maldives",
    "Malawi",
    "Mexico",
    "Malaysia",
    "Mozambique",
    "Namibia",
    "New Caledonia",
    "Niger",
    "Norfolk Island",
    "Nigeria",
    "Nicaragua",
    "Netherlands",
    "Norway",
    "Nepal",
    "Nauru",
    "Niue",
    "New Zealand",
    "Oman",
    "Panama",
    "Peru",
    "French Polynesia",
    "Papua New Guinea",
    "Philippines",
    "Pakistan",
    "Poland",
    "Saint Pierre and Miquelon",
    "Pitcairn",
    "Puerto Rico",
    "Palestine",
    "Portugal",
    "Palau",
    "Paraguay",
    "Qatar",
    "Réunion",
    "Romania",
    "Serbia",
    "Russian Federation",
    "Rwanda",
    "Saudi Arabia",
    "Solomon Islands",
    "Seychelles",
    "Sudan",
    "Sweden",
    "Singapore",
    "Saint Helena, Ascension and Tristan da Cunha",
    "Slovenia",
    "Svalbard and Jan Mayen",
    "Slovakia",
    "Sierra Leone",
    "San Marino",
    "Senegal",
    "Somalia",
    "Suriname",
    "South Sudan",
    "Sao Tome and Principe",
    "El Salvador",
    "Sint Maarten",
    "Syrian Arab Republic",
    "Eswatini",
    "Turks and Caicos Islands",
    "Chad",
    "French Southern Territories",
    "Togo",
    "Thailand",
    "Tajikistan",
    "Tokelau",
    "Timor-Leste",
    "Turkmenistan",
    "Tunisia",
    "Tonga",
    "Türkiye",
    "Trinidad and Tobago",
    "Tuvalu",
    "Taiwan",
    "Tanzania",
    "Ukraine",
    "Uganda",
    "United States Minor Outlying Islands",
    "United States of America",
    "Uruguay",
    "Uzbekistan",
    "Vatican City",
    "Saint Vincent and the Grenadines",
    "Venezuela",
    "British Virgin Islands",
    "U.S. Virgin Islands",
    "Viet Nam",
    "Vanuatu",
    "Wallis and Futuna",
    "Samoa",
    "Uncategorized",
    "Yemen",
    "Mayotte",
    "South Africa",
    "Zambia",
    "Zimbabwe",
];
pub static SubIndustry_names_ARRAY: &[&str] = &[
    "OilAndGasDrilling",
    "OilAndGasEquipmentAndServices",
    "IntegratedOilAndGas",
    "OilAndGasExplorationAndProduction",
    "OilAndGasRefiningAndMarketing",
    "OilAndGasStorageAndTransportation",
    "CoalAndConsumableFuels",
    "CommodityChemicals",
    "DiversifiedChemicals",
    "FertilizersAndAgriculturalChemicals",
    "IndustrialGases",
    "SpecialtyChemicals",
    "ConstructionMaterials",
    "MetalGlassAndPlasticContainers",
    "PaperAndPlasticPackagingProductsAndMaterials",
    "Aluminum",
    "DiversifiedMetalsAndMining",
    "Copper",
    "Gold",
    "PreciousMetalsAndMinerals",
    "Silver",
    "Steel",
    "ForestProducts",
    "PaperProducts",
    "AerospaceAndDefense",
    "BuildingProducts",
    "ConstructionAndEngineering",
    "ElectricalComponentsAndEquipment",
    "HeavyElectricalEquipment",
    "IndustrialConglomerates",
    "ConstructionMachineryAndHeavyTransportationEquipment",
    "AgriculturalAndFarmMachinery",
    "IndustrialMachinerySuppliesAndComponents",
    "TradingCompaniesAndDistributors",
    "CommercialPrinting",
    "EnvironmentalAndFacilitiesServices",
    "OfficeServicesAndSupplies",
    "DiviersifiedSupportServices",
    "SecurityAndAlarmServices",
    "HumanResourcesAndEmploymentServices",
    "ResearchAndConsultingServices",
    "DataProcessingAndOutsourcedServices",
    "AirFreightAndLogistics",
    "PassengerAirlines",
    "MarineTransportation",
    "RailTransportation",
    "CargoGroundTransportation",
    "PassengerGroundTransportation",
    "AirportServices",
    "HighwaysAndRailtracks",
    "MarinePortsAndServices",
    "AutomotivePartsAndEquipment",
    "TiresAndRubber",
    "AutomobileManufacturers",
    "MotorcycleManufacturers",
    "ConsumerElectronics",
    "HomeFurnishings",
    "Homebuilding",
    "HouseholdAppliances",
    "HousewaresAndSpecialties",
    "LeisureProducts",
    "ApparelAccessoriesAndLuxuryGoods",
    "Footwear",
    "Textiles",
    "CasinosAndGaming",
    "HotelsResortsAndCruiseLines",
    "LeisureFacilities",
    "Restaurants",
    "EducationServices",
    "SpecializedConsumerServices",
    "Distributors",
    "BroadlineRetail",
    "ApparelRetail",
    "ComputerAndElectronicsretail",
    "HomeImprovementRetail",
    "OtherSpecialtyRetail",
    "AutomotiveRetail",
    "HomefurnishingRetail",
    "DrugRetail",
    "FoodDistributors",
    "FoodRetail",
    "ConsumerStaplesMerchandiseRetail",
    "Brewers",
    "DistillersAndVintners",
    "SoftDrinksAndNonAlcoholicBeverages",
    "AgriculturalProductsAndServices",
    "PackagedFoodsAndMeats",
    "Tobacco",
    "HouseholdProducts",
    "PersonalCareProducts",
    "HealthCareEquipment",
    "HealthCareSupplies",
    "HealthCareDistributors",
    "HealthCareServices",
    "HealthCareFacilities",
    "ManagedHealthCare",
    "HealthCareTechnology",
    "Biotechnology",
    "Pharmaceuticals",
    "LifeSciencesToolsAndServices",
    "DiversifiedBanks",
    "RegionalBanks",
    "DiversifiedFinancialServices",
    "MultiSectorHoldings",
    "SpecializedFinance",
    "CommercialAndResidentialMortgageFinance",
    "TransactionAndPaymentProcessingServices",
    "ConsumerFinance",
    "AssetManagementAndCustodyBanks",
    "InvestmentBankingAndBrokerage",
    "DiversifiedCapitalMarkets",
    "FinancialExchangesAndData",
    "MortgageRealEstateInvestmentTrusts",
    "InsuranceBrokers",
    "LifeAndHealthInsurance",
    "MultilineInsurance",
    "PropertyAndCasualtyInsurance",
    "Reinsurance",
    "ITConsultingAndOtherServices",
    "InternetServicesAndInfrastructure",
    "ApplicationSoftware",
    "SystemsSoftware",
    "CommunicationsEquipment",
    "TechnologyHardwareStorageAndPeripherals",
    "ElectronicEquipmentAndInstruments",
    "ElectronicComponents",
    "ElectronicManufacturingServices",
    "TechnologyDistributors",
    "SemiconductorMaterialsAndEquipment",
    "Semiconductors",
    "AlternativeCarriers",
    "IntegratedTelecommunicationServices",
    "WirelessTelecommunicationServices",
    "Advertising",
    "Broadcasting",
    "CableAndSatellite",
    "Publishing",
    "MoviesAndEntertainment",
    "InteractiveHomeEntertainment",
    "InteractiveMediaAndServices",
    "ElectricUtilities",
    "GasUtilities",
    "MultiUtilities",
    "WaterUtilities",
    "IndependentPowerProducersAndEnergyTraders",
    "RenewableElectricity",
    "DiversifiedREITs",
    "IndustrialREITs",
    "HotelAndResortREITs",
    "OfficeREITs",
    "HealthCareREITs",
    "MultiFamilyResidentialREITs",
    "SingleFamilyResidentialREITs",
    "RetailREITs",
    "OtherSpecializedREITs",
    "SelfStorageREITs",
    "TelecomTowerREITs",
    "TimberREITs",
    "DataCenterREITs",
    "DiversifiedRealEstateActivities",
    "RealEstateOperatingCompanies",
    "RealEstateDevelopment",
    "RealEstateServices",
];

// Basic tests
#[cfg(test)]
mod tests {
    use super::*;
    use std::collections::HashSet;

    #[test]
    fn test_currency_codes() {
        let mut seen = HashSet::new();
        for code in Currency_CODES_ARRAY {
            assert!(!seen.contains(code), "Duplicate currency code: {}", code);
            seen.insert(*code);
        }
    }

    #[test]
    fn test_currency_code_name_alignment() {
        assert_eq!(
            Currency_VARIANTS.len(),
            CurrencyName_ARRAY.len(),
            "Currency code and display-name tables must stay aligned",
        );
    }

    #[test]
    fn test_currency_names_present() {
        assert!(CurrencyName_ARRAY.iter().all(|name| !name.is_empty()));
    }
    #[test]
    fn test_subindustry_names() {
        let mut seen = HashSet::new();
        for name in SubIndustry_names_ARRAY {
            assert!(!seen.contains(name), "Duplicate subindustry name: {}", name);
            seen.insert(*name);
        }
    }
    #[test]
    fn test_country_codes() {
        let mut seen = HashSet::new();
        for code in CountryCode_VARIANTS {
            assert!(!seen.contains(code), "Duplicate country code: {}", code);
            seen.insert(*code);
        }
    }
    #[test]
    fn test_country_code_alignment() {
        assert_eq!(CountryCode_VARIANTS.len(), CountryCode3_VARIANTS.len());
        assert_eq!(CountryCode_VARIANTS.len(), CountryNames_ARRAY.len());
    }
    #[test]
    fn test_country_names() {
        let mut seen = HashSet::new();
        for name in CountryNames_ARRAY {
            assert!(!seen.contains(name), "Duplicate country name: {}", name);
            seen.insert(*name);
        }
    }
}
