name: Setup Python Caching
description: 'Setup pip caching'

runs:
  using: 'composite'
  steps:
    ##########
    # Caches #
    ##########
    ################
    # Pip Cache
    - name: Setup pip cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/pyproject.toml', '**/setup.py') }}
        restore-keys: ${{ runner.os }}-pip-
