name: Setup Python
description: 'Ensure python is installed, and setup pypi caching'

inputs:
  version:
    type: choice
    description: "Version to install"
    options: 
        - '3.7'
        - '3.8'
        - '3.9'
        - '3.10'
        - '3.11'

runs:
  using: 'composite'
  steps:
    ##########
    # Caches #
    ##########
    ################
    - name: Setup Pip caching
      uses: ./.github/workflows/actions/setup-python-cache

    ###############################
    # Language and Compiler Setup #
    ###############################
    - name: Set up Python ${{ inputs.version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
        cache: "pip"
        cache-dependency-path: |
          "**/pyproject.toml"
          "**/setup.py"
