[package]
name = "finance_enums"
version = "0.7.0"
authors = ["PrettyGoodCapital <prettygoodcapital@gmail.com>"]
edition = "2021"
license = "Apache-2.0"
readme = "../README.md"
repository = "https://github.com/prettygoodcapital/finance enums"
description = "Standard financial enumerations"

[lib]
name = "finance_enums"
path = "src/lib.rs"
crate-type = ["rlib", "cdylib", "staticlib"]

[features]
default = []
polars = ["dep:polars-core"]

[dependencies]
polars-core = { version = "0.46", optional = true, default-features = false, features = ["dtype-categorical"] }

[profile.test.junit]
path = "junit.xml"
